print("-"*35)
print("Tugas 1 SISOP Kelas A")
print("-"*35)
print("Nama : Andry Syva Maldini")
print("NPM : 21083010085")
print("-"*35)
print("Notes:")
print("-"*35)
print("Hallo Dunia!")
print("Ini adalah skrip Bash pertamaku di Linux!")
